# Generated by Django 4.2.7 on 2023-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yslyga', models.CharField(max_length=1, verbose_name='Выберите услугу')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('coment', models.TextField(verbose_name='Коментарий')),
            ],
        ),
    ]
